"use client";

import React, { useState } from "react";
import { Download, Sparkles, Columns } from "lucide-react";
import { PDFDownloadLink, Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const pdfStyles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 13,
    fontFamily: "Helvetica",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    minHeight: "100%",
  },
  title: {
    fontSize: 22,
    textAlign: "center",
    marginBottom: 24,
    fontWeight: "bold",
  },
  table: {
    // display: "table", // Removed: not a valid value for @react-pdf/renderer
    width: "auto",
    marginBottom: 16,
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    overflow: "hidden",
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    alignItems: "center",
  },
  cellHeader: {
    fontWeight: "bold",
    backgroundColor: "#222",
    color: "#fff",
    padding: 10,
    fontSize: 15,
    flex: 1,
    textAlign: "left",
    borderRightWidth: 1,
    borderRightColor: "#444",
  },
  cell: {
    padding: 10,
    fontSize: 13,
    flex: 1,
    textAlign: "left",
    borderRightWidth: 1,
    borderRightColor: "#eee",
    color: "#222",
  },
  lastCell: {
    borderRightWidth: 0,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 10,
    color: "#888",
  },
});

function ComparisonPDF({ left, right, data }: { left: string; right: string; data: { point: string; left: string; right: string }[] }) {
  return (
    <Document>
      <Page size="A4" style={pdfStyles.page} wrap>
        <Text style={pdfStyles.title}>AI Comparison: {left} vs {right}</Text>
        <View style={pdfStyles.table}>
          <View style={pdfStyles.row}>
            <Text style={pdfStyles.cellHeader}>Feature</Text>
            <Text style={pdfStyles.cellHeader}>{left}</Text>
            <Text style={[pdfStyles.cellHeader, pdfStyles.lastCell]}>{right}</Text>
          </View>
          {data.map((row, idx) => (
            <View style={[pdfStyles.row, { backgroundColor: idx % 2 === 1 ? '#f3f4f6' : '#fff' }]} key={idx}>
              <Text style={pdfStyles.cell}>{row.point}</Text>
              <Text style={pdfStyles.cell}>{row.left}</Text>
              <Text style={[pdfStyles.cell, pdfStyles.lastCell]}>{row.right}</Text>
            </View>
          ))}
        </View>
        <Text style={pdfStyles.footer}>Generated by ExplainX</Text>
      </Page>
    </Document>
  );
}

export default function ComparisonToolClient() {
  const [left, setLeft] = useState("");
  const [right, setRight] = useState("");
  const [data, setData] = useState<{ point: string; left: string; right: string }[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showResult, setShowResult] = useState(false);

  const handleCompare = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setShowResult(false);
    setData([]);
    try {
      const res = await fetch("/api/tools/comparison-tool", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ left, right }),
      });
      const result = await res.json();
      if (!res.ok) throw new Error(result.error || "Failed to generate comparison");
      if (!Array.isArray(result.comparison) || result.comparison.length === 0) {
        throw new Error("Comparison failed. Please try again.");
      }
      setData(result.comparison);
      setShowResult(true);
    } catch (err: any) {
      setError(err.message || "Unknown error");
      setShowResult(false);
    } finally {
      setLoading(false);
    }
  };

  const handleBack = () => {
    setShowResult(false);
    setData([]);
    setError(null);
  };

  const handleFillSample = () => {
    setLeft("iOS");
    setRight("Android");
  };

  return (
    <main className="min-h-screen flex flex-col items-center justify-center bg-background text-foreground transition-colors duration-500 pt-24 md:pt-28 pb-12">
      <div className="w-full max-w-3xl px-4 py-8 bg-white dark:bg-zinc-900 rounded-2xl shadow-2xl border border-gray-200 dark:border-zinc-700 flex flex-col items-center animate-fade-in">
        <div className="w-full flex flex-col items-center mb-6">
          <div className="flex flex-col md:flex-row items-center gap-2 mb-2">
            <span className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-gray-100">AI Comparison Tool</span>
            <span className="text-2xl md:text-3xl font-bold bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 px-2 rounded-md ml-2">Try it now</span>
          </div>
          <div className="flex items-center gap-2 mt-2">
            <span className="text-lg text-gray-900 dark:text-gray-100">Compare any two things or</span>
            <button
              type="button"
              className="ml-2 px-4 py-2 rounded-lg bg-blue-100 text-blue-700 font-semibold hover:bg-blue-200 transition text-base"
              onClick={handleFillSample}
            >
              Try with sample
            </button>
          </div>
        </div>
        {!showResult ? (
          <form
            onSubmit={handleCompare}
            className="w-full bg-white dark:bg-zinc-900 rounded-xl shadow p-6 flex flex-col gap-6 border border-gray-200 dark:border-zinc-700"
          >
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="font-semibold mb-2 text-lg text-gray-900 dark:text-gray-100" htmlFor="left">First Item</label>
                <input
                  id="left"
                  type="text"
                  className="border border-input dark:border-zinc-700 rounded-lg p-3 bg-background dark:bg-zinc-800 text-foreground dark:text-gray-100 focus:ring-2 focus:ring-primary outline-none transition w-full"
                  placeholder="e.g., iOS, React, Tesla..."
                  value={left}
                  onChange={e => setLeft(e.target.value)}
                  required
                />
              </div>
              <div>
                <label className="font-semibold mb-2 text-lg text-gray-900 dark:text-gray-100" htmlFor="right">Second Item</label>
                <input
                  id="right"
                  type="text"
                  className="border border-input dark:border-zinc-700 rounded-lg p-3 bg-background dark:bg-zinc-800 text-foreground dark:text-gray-100 focus:ring-2 focus:ring-primary outline-none transition w-full"
                  placeholder="e.g., Android, Vue, Ford..."
                  value={right}
                  onChange={e => setRight(e.target.value)}
                  required
                />
              </div>
            </div>
            <button
              type="submit"
              className="bg-indigo-600 text-white px-6 py-2 rounded-lg font-semibold hover:bg-indigo-700 dark:hover:bg-indigo-500 transition self-end flex items-center gap-2"
              disabled={loading}
            >
              {loading ? (
                <>
                  <Sparkles className="w-5 h-5 animate-pulse" />
                  Comparing...
                </>
              ) : (
                <>
                  <Columns className="w-5 h-5" />
                  Compare
                </>
              )}
            </button>
            {error && <div className="text-red-500 mt-2 font-semibold">{error}</div>}
          </form>
        ) : (
          <div className="w-full flex flex-col gap-6 animate-slide-in mt-4">
            <div className="w-full bg-white dark:bg-zinc-900 rounded-xl shadow p-6 border border-gray-200 dark:border-zinc-700 flex flex-col relative">
              <div className="absolute top-4 right-4 z-10">
                <PDFDownloadLink
                  document={<ComparisonPDF left={left} right={right} data={data} />}
                  fileName="comparison.pdf"
                  style={{ textDecoration: "none" }}
                >
                  {({ loading }) => (
                    <button
                      className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg font-semibold text-base shadow-md hover:bg-indigo-700 dark:hover:bg-indigo-500 transition focus:outline-none focus:ring-2 focus:ring-indigo-500 mb-6"
                      title="Download as PDF"
                    >
                      <Download className="w-5 h-5" />
                      {loading ? "Preparing PDF..." : "Download PDF"}
                    </button>
                  )}
                </PDFDownloadLink>
              </div>
              <h2 className="text-xl font-semibold mb-4 text-gray-900 dark:text-gray-100">Comparison Table</h2>
              <div className="overflow-x-auto">
                <table className="min-w-full border border-gray-300 dark:border-zinc-700 rounded-xl overflow-hidden text-base">
                  <thead className="bg-zinc-900 text-white">
                    <tr>
                      <th className="px-5 py-3 font-bold text-lg border-r border-zinc-700 text-left">Feature</th>
                      <th className="px-5 py-3 font-bold text-lg border-r border-zinc-700 text-left">{left}</th>
                      <th className="px-5 py-3 font-bold text-lg text-left">{right}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {data.map((row, idx) => (
                      <tr
                        key={idx}
                        className={
                          (idx % 2 === 0 ? "bg-zinc-900/80 dark:bg-zinc-900" : "bg-zinc-800/80 dark:bg-zinc-800") +
                          " border-b border-zinc-700 hover:bg-zinc-700/60 transition"
                        }
                      >
                        <td className="px-5 py-3 border-r border-zinc-700 text-left align-top font-semibold">{row.point}</td>
                        <td className="px-5 py-3 border-r border-zinc-700 text-left align-top">{row.left}</td>
                        <td className="px-5 py-3 text-left align-top">{row.right}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <button
                onClick={handleBack}
                className="w-full mt-4 bg-gray-200 dark:bg-zinc-800 text-gray-900 dark:text-gray-100 py-2 rounded-xl font-semibold shadow hover:bg-gray-300 dark:hover:bg-zinc-700 transition focus:outline-none focus:ring-2 focus:ring-indigo-500"
              >
                Back & Compare Again
              </button>
            </div>
          </div>
        )}
      </div>
      <style jsx global>{`
        @keyframes fade-in {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in {
          animation: fade-in 0.6s cubic-bezier(0.4,0,0.2,1);
        }
        @keyframes slide-in {
          from { opacity: 0; transform: translateY(40px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-slide-in {
          animation: slide-in 0.7s cubic-bezier(0.4,0,0.2,1);
        }
      `}</style>
    </main>
  );
} 