'use client';

import React, { useState } from 'react';
import { Download, Upload, RotateCcw, Sparkles, CheckCircle, Edit, FileText } from 'lucide-react';
import { PDFDownloadLink, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import pdfToText from 'react-pdftotext';

// PDF styles for export
const pdfStyles = StyleSheet.create({
  page: {
    padding: 20,
    fontSize: 12,
    fontFamily: 'Helvetica',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    minHeight: '100%',
  },
  title: {
    fontSize: 20,
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: 'bold',
  },
  notes: {
    fontSize: 13,
    marginBottom: 20,
    color: '#333',
  },
  question: {
    fontWeight: 'bold',
    marginBottom: 6,
    fontSize: 14,
  },
  answer: {
    fontSize: 12,
    marginBottom: 8,
    color: '#444',
  },
  marks: {
    fontSize: 11,
    color: '#666',
    marginBottom: 4,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 10,
    color: '#888',
  },
});

// PDF Document component for exam export
const ExamPDF = ({ notes, questions, answers, marks, requestedMarks }: { notes: string; questions: any[]; answers?: string[]; marks?: number[]; requestedMarks?: number }) => (
  <Document>
    <Page size="A4" style={pdfStyles.page} wrap>
      <Text style={pdfStyles.title}>Exam Preparation Report</Text>
      <Text style={{ ...pdfStyles.title, fontSize: 16, marginBottom: 10, textAlign: 'left' }}>Study Notes</Text>
      <Text style={pdfStyles.notes}>{notes}</Text>
      <Text style={{ ...pdfStyles.title, fontSize: 16, marginBottom: 10, textAlign: 'left', marginTop: 20 }}>Exam Paper</Text>
      {questions.map((q, idx) => (
        <View key={idx} style={{ marginBottom: 12 }}>
          <Text style={pdfStyles.question}>{idx + 1}. [{q.type}] {q.question} ({q.marks} marks)</Text>
          {q.options && Array.isArray(q.options) && (
            <View style={{ marginLeft: 10, marginBottom: 4 }}>
              {q.options.map((opt: string, oidx: number) => (
                <Text key={oidx} style={pdfStyles.answer}>
                  {String.fromCharCode(65 + oidx)}. {opt} {answers && answers[idx] === opt ? '(Selected)' : ''}
                </Text>
              ))}
            </View>
          )}
          {q.type === 'True/False' && (
            <View style={{ marginLeft: 10, marginBottom: 4 }}>
              {['True', 'False'].map((opt, oidx) => (
                <Text key={oidx} style={pdfStyles.answer}>
                  {opt} {answers && answers[idx] === opt ? '(Selected)' : ''}
                </Text>
              ))}
            </View>
          )}
          {q.type === 'Short Answer' && answers && answers[idx] && (
            <Text style={pdfStyles.answer}>Your Answer: {answers[idx]}</Text>
          )}
          {marks && marks[idx] !== undefined && (
            <Text style={pdfStyles.marks}>Marks Awarded: {marks[idx]}</Text>
          )}
        </View>
      ))}
      <View style={{ marginTop: 30, borderTop: '1px solid #ccc', paddingTop: 10 }}>
        <Text style={{ fontSize: 12, fontWeight: 'bold', marginBottom: 4 }}>Summary</Text>
        <Text style={pdfStyles.marks}>Requested Total Marks: {requestedMarks}</Text>
        <Text style={pdfStyles.marks}>Actual Total Marks: {questions.reduce((acc, q) => acc + (q.marks || 0), 0)}</Text>
        {marks && marks.length > 0 && (
          <Text style={pdfStyles.marks}>Total Marks Awarded: {marks.reduce((acc, m) => acc + (typeof m === 'number' && !isNaN(m) ? m : 0), 0)}</Text>
        )}
      </View>
      <Text style={pdfStyles.footer}>Generated by ExplainX Exam Preparation Tool</Text>
    </Page>
  </Document>
);

// Add a function for Jaccard similarity
function jaccardSimilarity(a: string, b: string): number {
  const setA = new Set(a.toLowerCase().split(/\W+/).filter(Boolean));
  const setB = new Set(b.toLowerCase().split(/\W+/).filter(Boolean));
  const intersection = new Set([...setA].filter(x => setB.has(x)));
  const union = new Set([...setA, ...setB]);
  return union.size === 0 ? 0 : intersection.size / union.size;
}

export default function ExamPreparationGeneratorClient() {
  const [file, setFile] = useState<File | null>(null);
  const [questionTypes, setQuestionTypes] = useState<string[]>(['MCQ', 'Short Answer', 'True/False']);
  const [totalMarks, setTotalMarks] = useState<number>(20);
  const [notes, setNotes] = useState('');
  const [questions, setQuestions] = useState<any[]>([]);
  const [answers, setAnswers] = useState<string[]>([]);
  const [marks, setMarks] = useState<number[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showResult, setShowResult] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [dragActive, setDragActive] = useState(false);
  const [requestedMarks, setRequestedMarks] = useState<number>(20);
  const [correctAnswers, setCorrectAnswers] = useState<string[]>([]);
  const [feedback, setFeedback] = useState<string[]>([]);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile && selectedFile.type === 'application/pdf') {
      setFile(selectedFile);
      setError(null);
    } else {
      setError('Please select a valid PDF file');
    }
  };

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!file) {
      setError('Please upload a PDF file');
      return;
    }
    setLoading(true);
    setError(null);
    setNotes('');
    setQuestions([]);
    setAnswers([]);
    setMarks([]);
    setShowResult(false);
    setSubmitted(false);
    setRequestedMarks(totalMarks); // Set requested marks
    try {
      // Extract text from PDF
      const text = await pdfToText(file);
      // Send extracted text to backend
      const res = await fetch('/api/tools/exam-preparation-generator', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text, questionTypes: questionTypes.join(','), totalMarks: String(totalMarks) }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to generate exam');
      setNotes(data.notes);
      setQuestions(data.questions);
      setAnswers(Array(data.questions.length).fill(''));
      setMarks(Array(data.questions.length).fill(undefined));
      setCorrectAnswers(data.questions.map((q: any) => q.answer || ''));
      setShowResult(true);
    } catch (err: any) {
      setError(err.message || 'Unknown error');
      setShowResult(false);
    } finally {
      setLoading(false);
    }
  };

  const handleBack = () => {
    setShowResult(false);
    setNotes('');
    setQuestions([]);
    setAnswers([]);
    setMarks([]);
    setFile(null);
    setError(null);
    setSubmitted(false);
  };

  const handleAnswerChange = (idx: number, value: string) => {
    setAnswers((prev) => {
      const arr = [...prev];
      arr[idx] = value;
      return arr;
    });
  };

  const handleSubmitExam = () => {
    setSubmitted(true);
    setLoading(true);
    setError(null);
    const newMarks: number[] = [];
    const newFeedback: string[] = [];
    questions.forEach((q, idx) => {
      const userAnswer = (answers[idx] || '').trim();
      const correctAnswer = (correctAnswers[idx] || '').trim();
      if (q.type === 'MCQ' || q.type === 'True/False') {
        if (userAnswer.toLowerCase() === correctAnswer.toLowerCase()) {
          newMarks.push(q.marks);
          newFeedback.push('Correct!');
        } else {
          newMarks.push(0);
          newFeedback.push('Incorrect.');
        }
      } else if (q.type === 'Short Answer') {
        const similarity = jaccardSimilarity(userAnswer, correctAnswer);
        if (similarity >= 0.8) {
          newMarks.push(q.marks);
          newFeedback.push('Great answer!');
        } else if (similarity >= 0.5) {
          newMarks.push(1);
          newFeedback.push('Partially correct.');
        } else {
          newMarks.push(0);
          newFeedback.push('Not enough match.');
        }
      } else {
        newMarks.push(0);
        newFeedback.push('No answer.');
      }
    });
    setMarks(newMarks);
    setFeedback(newFeedback);
    setLoading(false);
  };

  const handleMarkChange = (idx: number, value: string) => {
    setMarks((prev) => {
      const arr = [...prev];
      arr[idx] = Number(value);
      return arr;
    });
  };

  const totalSelfMarks = marks.reduce((acc, m) => acc + (typeof m === 'number' && !isNaN(m) ? m : 0), 0);
  const totalExamMarks = questions.reduce((acc, q) => acc + (q.marks || 0), 0);

  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(true);
  };
  const handleDragLeave = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
  };
  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const droppedFile = e.dataTransfer.files[0];
      if (droppedFile.type === 'application/pdf') {
        setFile(droppedFile);
        setError(null);
      } else {
        setError('Please select a valid PDF file');
      }
    }
  };
  const fileInputRef = React.useRef<HTMLInputElement>(null);
  const handleUploadAreaClick = () => {
    fileInputRef.current?.click();
  };

  const handleQuestionTypeToggle = (type: string) => {
    setQuestionTypes((prev) =>
      prev.includes(type) ? prev.filter((t) => t !== type) : [...prev, type]
    );
  };

  return (
    <main className="min-h-screen flex flex-col items-center justify-center bg-background text-foreground transition-colors duration-500 pt-24 md:pt-28 pb-12">
      <div className="w-full max-w-4xl px-4 py-8 bg-white dark:bg-zinc-900 rounded-2xl shadow-2xl border border-gray-200 dark:border-zinc-700 flex flex-col items-center animate-fade-in">
        <div className="w-full flex flex-col items-center mb-6">
          <div className="flex flex-col md:flex-row items-center gap-2 mb-2">
            <span className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-gray-100">Exam Preparation Generator</span>
            <span className="text-2xl md:text-3xl font-bold bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 px-2 rounded-md ml-2">AI Powered</span>
          </div>
          <div className="flex items-center gap-2 mt-2">
            <span className="text-lg text-gray-900 dark:text-gray-100">Upload a PDF to generate notes and a custom exam</span>
          </div>
        </div>
        {!showResult ? (
          <form
            onSubmit={handleGenerate}
            className="w-full bg-white dark:bg-zinc-900 rounded-xl shadow p-6 flex flex-col gap-6 border border-gray-200 dark:border-zinc-700"
          >
            <div>
              <label className="font-semibold mb-2 text-lg text-gray-900 dark:text-gray-100" htmlFor="pdfFile">
                Upload PDF File
              </label>
              <div
                className={`border-2 border-dashed rounded-lg p-6 text-center transition-colors cursor-pointer select-none ${dragActive ? 'border-blue-400 dark:border-blue-500 bg-blue-50 dark:bg-blue-900/20' : 'border-gray-300 dark:border-zinc-600'}`}
                onClick={handleUploadAreaClick}
                onDragOver={handleDragOver}
                onDragLeave={handleDragLeave}
                onDrop={handleDrop}
                tabIndex={0}
                role="button"
                aria-label="Upload PDF by clicking or dragging"
              >
                <Upload className="mx-auto h-12 w-12 text-gray-400 dark:text-gray-500 mb-4 pointer-events-none" />
                <input
                  id="pdfFile"
                  type="file"
                  accept=".pdf"
                  onChange={handleFileUpload}
                  className="hidden"
                  ref={fileInputRef}
                />
                <div className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-2">
                  {file ? file.name : 'Click or drag a PDF here to upload'}
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  {file ? 'File selected' : 'PDF files only'}
                </div>
                {dragActive && (
                  <div className="absolute inset-0 bg-blue-100/60 dark:bg-blue-900/40 rounded-lg flex items-center justify-center pointer-events-none">
                    <span className="text-blue-700 dark:text-blue-200 font-semibold text-lg">Drop your PDF here</span>
                  </div>
                )}
              </div>
            </div>
            <div className="flex flex-col md:flex-row gap-4">
              <div className="flex flex-col gap-2 flex-1">
                <label className="font-semibold text-gray-900 dark:text-gray-100">Question Types</label>
                <div className="flex gap-3 flex-wrap">
                  {['MCQ', 'Short Answer', 'True/False'].map((type) => (
                    <button
                      key={type}
                      type="button"
                      className={`px-4 py-2 rounded-lg font-semibold border transition ${questionTypes.includes(type) ? 'bg-indigo-600 text-white border-indigo-600' : 'bg-gray-100 dark:bg-zinc-800 text-gray-800 dark:text-gray-100 border-gray-300 dark:border-zinc-600'}`}
                      onClick={() => handleQuestionTypeToggle(type)}
                    >
                      {type}
                    </button>
                  ))}
                </div>
              </div>
              <div className="flex flex-col gap-2 flex-1">
                <label className="font-semibold text-gray-900 dark:text-gray-100">Total Marks</label>
                <input
                  type="number"
                  min={5}
                  max={100}
                  value={totalMarks}
                  onChange={(e) => {
                    setTotalMarks(Number(e.target.value));
                    setRequestedMarks(Number(e.target.value));
                  }}
                  className="px-4 py-2 rounded-lg border border-gray-300 dark:border-zinc-600 bg-white dark:bg-zinc-800 text-gray-900 dark:text-gray-100 font-medium"
                />
              </div>
            </div>
            <button
              type="submit"
              className="bg-indigo-600 text-white px-6 py-2 rounded-lg font-semibold hover:bg-indigo-700 dark:hover:bg-indigo-500 transition self-end flex items-center gap-2"
              disabled={loading || !file}
            >
              {loading ? (
                <>
                  <Sparkles className="w-5 h-5 animate-pulse" />
                  Generating...
                </>
              ) : (
                <>
                  <RotateCcw className="w-5 h-5" />
                  Generate Notes & Exam
                </>
              )}
            </button>
            {error && <div className="text-red-500 mt-2 font-semibold">{error}</div>}
          </form>
        ) : (
          <div className="w-full flex flex-col gap-6 animate-slide-in mt-4">
            {/* Notes Display */}
            <div className="w-full bg-white dark:bg-zinc-900 rounded-xl shadow p-6 border border-gray-200 dark:border-zinc-700">
              <div className="flex items-center gap-2 mb-2">
                <FileText className="w-5 h-5 text-indigo-600" />
                <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Generated Notes</h2>
              </div>
              <div className="text-gray-800 dark:text-gray-200 whitespace-pre-line text-base">{notes}</div>
            </div>
            {/* Exam Display */}
            <div className="w-full bg-white dark:bg-zinc-900 rounded-xl shadow p-6 border border-gray-200 dark:border-zinc-700">
              <div className="flex items-center gap-2 mb-2">
                <Edit className="w-5 h-5 text-indigo-600" />
                <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Generated Exam</h2>
              </div>
              {questions.map((q, idx) => (
                <div key={idx} className="mb-6">
                  <div className="font-semibold text-gray-900 dark:text-gray-100 mb-1">
                    {idx + 1}. [{q.type}] {q.question} <span className="text-sm text-gray-500">({q.marks} marks)</span>
                  </div>
                  {q.options && Array.isArray(q.options) && (
                    <div className="mb-2 text-gray-700 dark:text-gray-200">Options: {q.options.join(', ')}</div>
                  )}
                  {!submitted ? (
                    q.type === 'MCQ' ? (
                      <div className="flex flex-col gap-2">
                        {q.options && Array.isArray(q.options) && q.options.map((opt: string, oidx: number) => (
                          <label key={oidx} className="flex items-center text-gray-900 dark:text-gray-100">
                            <input
                              type="radio"
                              name={`question-${idx}`}
                              value={opt}
                              checked={answers[idx] === opt}
                              onChange={() => handleAnswerChange(idx, opt)}
                              className="mr-2"
                            />
                            {opt}
                          </label>
                        ))}
                      </div>
                    ) : q.type === 'True/False' ? (
                      <div className="flex flex-col gap-2">
                        {['True', 'False'].map((opt, oidx) => (
                          <label key={oidx} className="flex items-center text-gray-900 dark:text-gray-100">
                            <input
                              type="radio"
                              name={`question-${idx}`}
                              value={opt}
                              checked={answers[idx] === opt}
                              onChange={() => handleAnswerChange(idx, opt)}
                              className="mr-2"
                            />
                            {opt}
                          </label>
                        ))}
                      </div>
                    ) : (
                      <textarea
                        className="w-full min-h-[60px] rounded-lg border border-gray-300 dark:border-zinc-600 bg-white dark:bg-zinc-800 text-gray-900 dark:text-gray-100 p-2 mt-1"
                        placeholder="Write your answer here..."
                        value={answers[idx] || ''}
                        onChange={(e) => handleAnswerChange(idx, e.target.value)}
                      />
                    )
                  ) : (
                    <div className="bg-gray-100 dark:bg-zinc-800 rounded-lg p-2 mt-1 text-gray-900 dark:text-gray-100">
                      <span className="font-medium">Your Answer:</span> {answers[idx]}
                    </div>
                  )}
                  {submitted && (
                    <div className="mt-2 text-gray-700 dark:text-gray-200">
                      <span className="font-medium">AI Marks:</span> {marks[idx] !== undefined ? marks[idx] : 'N/A'}
                    </div>
                  )}
                  {submitted && (
                    <div className="mt-2 text-gray-700 dark:text-gray-200">
                      <span className="font-medium">AI Feedback:</span> {feedback[idx] || 'No feedback yet.'}
                    </div>
                  )}
                </div>
              ))}
              {!submitted && (
                <button
                  onClick={handleSubmitExam}
                  className="bg-green-600 text-white px-6 py-2 rounded-lg font-semibold hover:bg-green-700 transition flex items-center gap-2 mt-4"
                  disabled={loading}
                >
                  <CheckCircle className="w-5 h-5" /> Submit & Get AI Review
                </button>
              )}
              {submitted && (
                <div className="mt-4 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
                  <p className="text-blue-700 dark:text-blue-300 text-sm text-center">
                    Total Marks Awarded: <span className="font-bold">{totalSelfMarks}</span> / {totalExamMarks}
                  </p>
                  {totalSelfMarks !== requestedMarks && (
                    <p className="text-red-500 text-sm text-center mt-2">
                      Warning: Total marks awarded ({totalSelfMarks}) do not match requested total ({requestedMarks}).
                    </p>
                  )}
                </div>
              )}
            </div>
            <div className="flex flex-col md:flex-row gap-4 mt-2">
              <PDFDownloadLink
                document={<ExamPDF notes={notes} questions={questions} answers={answers} marks={marks} requestedMarks={requestedMarks} />}
                fileName="exam-paper.pdf"
                style={{ textDecoration: 'none' }}
              >
                {({ loading }) => (
                  <button
                    className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg font-semibold text-base shadow-md hover:bg-indigo-700 dark:hover:bg-indigo-500 transition focus:outline-none focus:ring-2 focus:ring-indigo-500"
                    title="Download as PDF"
                  >
                    <Download className="w-5 h-5" />
                    {loading ? 'Preparing PDF...' : 'Download PDF'}
                  </button>
                )}
              </PDFDownloadLink>
              <button
                onClick={handleBack}
                className="w-full md:w-auto bg-gray-200 dark:bg-zinc-800 text-gray-900 dark:text-gray-100 py-2 rounded-xl font-semibold shadow hover:bg-gray-300 dark:hover:bg-zinc-700 transition focus:outline-none focus:ring-2 focus:ring-indigo-500"
              >
                Back & Upload New File
              </button>
            </div>
          </div>
        )}
      </div>
      <style jsx global>{`
        @keyframes fade-in {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in {
          animation: fade-in 0.6s cubic-bezier(0.4,0,0.2,1);
        }
        @keyframes slide-in {
          from { opacity: 0; transform: translateY(40px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-slide-in {
          animation: slide-in 0.7s cubic-bezier(0.4,0,0.2,1);
        }
      `}</style>
    </main>
  );
} 