'use client';

import React, { useState } from 'react';
import { Download, Upload, RotateCcw, ChevronLeft, ChevronRight, Lightbulb, Sparkles } from 'lucide-react';
import { PDFDownloadLink, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

import pdfToText from 'react-pdftotext';

// PDF styles for flashcard export
const pdfStyles = StyleSheet.create({
  page: {
    padding: 20,
    fontSize: 12,
    fontFamily: 'Helvetica',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    minHeight: '100%',
  },
  title: {
    fontSize: 20,
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: 'bold',
  },
  flashcard: {
    marginBottom: 20,
    padding: 15,
    border: '1px solid #ccc',
    borderRadius: 8,
  },
  question: {
    fontWeight: 'bold',
    marginBottom: 8,
    fontSize: 14,
  },
  answer: {
    fontSize: 12,
    lineHeight: 1.4,
  },
  hint: {
    fontSize: 10,
    color: '#666',
    fontStyle: 'italic',
    marginTop: 5,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 10,
    color: '#888',
  },
});

// PDF Document component for flashcards
interface FlashcardPDFProps {
  flashcards: Array<{ question: string; answer: string; hint?: string }>;
}
const FlashcardPDF = ({ flashcards }: FlashcardPDFProps) => (
  <Document>
    <Page size="A4" style={pdfStyles.page} wrap>
      <Text style={pdfStyles.title}>Flashcards</Text>
      {flashcards.map((card, index) => (
        <View key={index} style={pdfStyles.flashcard}>
          <Text style={pdfStyles.question}>Question {index + 1}: {card.question}</Text>
          <Text style={pdfStyles.answer}>Answer: {card.answer}</Text>
          {card.hint && <Text style={pdfStyles.hint}>Hint: {card.hint}</Text>}
        </View>
      ))}
      <Text style={pdfStyles.footer}>Generated by ExplainX</Text>
    </Page>
  </Document>
);

interface Flashcard {
  question: string;
  answer: string;
  hint?: string;
}

const SAMPLE_FLASHCARDS: Flashcard[] = [
  {
    question: "What is the capital of France?",
    answer: "Paris",
    hint: "Think of the famous tower"
  },
  {
    question: "What is the chemical symbol for gold?",
    answer: "Au",
    hint: "From the Latin word 'aurum'"
  },
  {
    question: "Who wrote 'Romeo and Juliet'?",
    answer: "William Shakespeare",
    hint: "A famous English playwright"
  },
  {
    question: "What is the largest planet in our solar system?",
    answer: "Jupiter",
    hint: "It's a gas giant"
  },
  {
    question: "What year did World War II end?",
    answer: "1945",
    hint: "The year the atomic bombs were dropped"
  }
];

// Login Modal Component
function LoginModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  if (!open) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 dark:bg-black/70">
      <div className="bg-white dark:bg-zinc-900 rounded-xl shadow-2xl p-8 max-w-sm w-full flex flex-col items-center border border-gray-200 dark:border-zinc-700">
        <h2 className="text-xl font-bold mb-4 text-center text-gray-900 dark:text-gray-100">Login or Sign Up Required</h2>
        <p className="mb-6 text-center text-gray-700 dark:text-gray-300">To access more than 5 flashcards, please login or sign up.</p>
        <div className="flex gap-4 w-full justify-center">
          <button
            className="bg-indigo-600 text-white px-4 py-2 rounded-lg font-semibold hover:bg-indigo-700 transition w-1/2"
            onClick={() => window.location.href = '/login'}
          >
            Login
          </button>
          <button
            className="bg-gray-200 dark:bg-zinc-800 text-gray-800 dark:text-gray-100 px-4 py-2 rounded-lg font-semibold hover:bg-gray-300 dark:hover:bg-zinc-700 transition w-1/2"
            onClick={() => window.location.href = '/signup'}
          >
            Sign Up
          </button>
        </div>
        <button
          className="mt-6 text-sm text-gray-500 dark:text-gray-400 hover:underline"
          onClick={onClose}
        >
          Cancel
        </button>
      </div>
    </div>
  );
}

// Toast component
function Toast({ message, show }: { message: string; show: boolean }) {
  if (!show) return null;
  return (
    <div className="fixed bottom-8 left-1/2 transform -translate-x-1/2 z-50 bg-blue-600 text-white px-6 py-3 rounded-lg shadow-lg animate-fade-in">
      {message}
    </div>
  );
}

export default function PdfFlashcardGeneratorClient() {
  const [file, setFile] = useState<File | null>(null);
  const [pdfText, setPdfText] = useState('');
  const [flashcards, setFlashcards] = useState<Flashcard[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showResult, setShowResult] = useState(false);
  const [currentCard, setCurrentCard] = useState(0);
  const [flipped, setFlipped] = useState(false);
  const [showHint, setShowHint] = useState(false);
  const [showLoginModal, setShowLoginModal] = useState(false);
  const [showToast, setShowToast] = useState(false);
  const [dragActive, setDragActive] = useState(false);

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile && selectedFile.type === 'application/pdf') {
      setFile(selectedFile);
      setError(null);
      setLoading(true);
      setFlashcards([]);
      setShowResult(false);
      try {
        const text = await pdfToText(selectedFile);
        // Send extracted text to backend
        const res = await fetch('/api/tools/pdf-flashcard-generator', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ text }),
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error || 'Failed to generate flashcards');
        if (!data.flashcards || !Array.isArray(data.flashcards)) {
          throw new Error('Flashcard generation failed. Please try again.');
        }
        // Limit to 5 flashcards for non-logged users
        const limitedFlashcards = data.flashcards.slice(0, 5);
        setFlashcards(limitedFlashcards);
        setShowResult(true);
        setCurrentCard(0);
        setFlipped(false);
        setShowHint(false);
      } catch (err: any) {
        setError(err.message || 'Unknown error');
        setShowResult(false);
      } finally {
        setLoading(false);
      }
    } else {
      setError('Please select a valid PDF file');
    }
  };

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!file) {
      setError('Please upload a PDF file');
      return;
    }

    setLoading(true);
    setError(null);
    setFlashcards([]);
    setShowResult(false);

    try {
      const formData = new FormData();
      formData.append('file', file);

      const res = await fetch('/api/tools/pdf-flashcard-generator', {
        method: 'POST',
        body: formData,
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to generate flashcards');
      if (!data.flashcards || !Array.isArray(data.flashcards)) {
        throw new Error('Flashcard generation failed. Please try again.');
      }

      // Limit to 5 flashcards for non-logged users
      const limitedFlashcards = data.flashcards.slice(0, 5);
      setFlashcards(limitedFlashcards);
      setShowResult(true);
      setCurrentCard(0);
      setFlipped(false);
      setShowHint(false);
    } catch (err: any) {
      setError(err.message || 'Unknown error');
      setShowResult(false);
    } finally {
      setLoading(false);
    }
  };

  const handleBack = () => {
    setShowResult(false);
    setFlashcards([]);
    setError(null);
    setFile(null);
  };

  const handleFillSample = () => {
    setFlashcards(SAMPLE_FLASHCARDS);
    setShowResult(true);
    setCurrentCard(0);
    setFlipped(false);
    setShowHint(false);
  };

  const handleFlip = () => {
    // Disable flipping on the 5th card if at limit
    if (currentCard === 4 && flashcards.length === 5) return;
    setFlipped(!flipped);
  };

  const handlePrev = () => {
    setFlipped(false);
    setShowHint(false);
    setCurrentCard(Math.max(0, currentCard - 1));
  };

  const handleNext = () => {
    setFlipped(false);
    setShowHint(false);
    const nextCard = currentCard + 1;
    
    // Check if trying to access beyond 5th flashcard
    if (nextCard >= 5 && flashcards.length > 5) {
      setShowLoginModal(true);
      setShowToast(true);
      setTimeout(() => setShowToast(false), 2500);
      return;
    }
    
    setCurrentCard(Math.min(flashcards.length - 1, nextCard));
  };

  const currentFlashcard = flashcards[currentCard];

  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(true);
  };
  const handleDragLeave = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
  };
  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const droppedFile = e.dataTransfer.files[0];
      if (droppedFile.type === 'application/pdf') {
        setFile(droppedFile);
        setError(null);
      } else {
        setError('Please select a valid PDF file');
      }
    }
  };
  const fileInputRef = React.useRef<HTMLInputElement>(null);
  const handleUploadAreaClick = () => {
    fileInputRef.current?.click();
  };

  return (
    <main className="min-h-screen flex flex-col items-center justify-center bg-background text-foreground transition-colors duration-500 pt-24 md:pt-28 pb-12">
      <LoginModal open={showLoginModal} onClose={() => setShowLoginModal(false)} />
      <Toast message="Login to see and generate unlimited flashcards!" show={showToast} />
      <div className="w-full max-w-4xl px-4 py-8 bg-white dark:bg-zinc-900 rounded-2xl shadow-2xl border border-gray-200 dark:border-zinc-700 flex flex-col items-center animate-fade-in">
        {/* Try it now section */}
        <div className="w-full flex flex-col items-center mb-6">
          <div className="flex flex-col md:flex-row items-center gap-2 mb-2">
            <span className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-gray-100">Try it now.</span>
            <span className="text-2xl md:text-3xl font-bold bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 px-2 rounded-md ml-2">It takes 10s</span>
          </div>
          <div className="flex items-center gap-2 mt-2">
            <span className="text-lg text-gray-900 dark:text-gray-100">Upload a PDF or</span>
            <button
              type="button"
              className="ml-2 px-4 py-2 rounded-lg bg-blue-100 text-blue-700 font-semibold hover:bg-blue-200 transition text-base"
              onClick={handleFillSample}
            >
              Try with sample
            </button>
          </div>
        </div>

        {!showResult ? (
          <form
            onSubmit={handleGenerate}
            className="w-full bg-white dark:bg-zinc-900 rounded-xl shadow p-6 flex flex-col gap-6 border border-gray-200 dark:border-zinc-700"
          >
            <div>
              <label className="font-semibold mb-2 text-lg text-gray-900 dark:text-gray-100" htmlFor="pdfFile">
                Upload PDF File
              </label>
              <div
                className={`border-2 border-dashed rounded-lg p-6 text-center transition-colors cursor-pointer select-none ${dragActive ? 'border-blue-400 dark:border-blue-500 bg-blue-50 dark:bg-blue-900/20' : 'border-gray-300 dark:border-zinc-600'}`}
                onClick={handleUploadAreaClick}
                onDragOver={handleDragOver}
                onDragLeave={handleDragLeave}
                onDrop={handleDrop}
                tabIndex={0}
                role="button"
                aria-label="Upload PDF by clicking or dragging"
              >
                <Upload className="mx-auto h-12 w-12 text-gray-400 dark:text-gray-500 mb-4 pointer-events-none" />
                <input
                  id="pdfFile"
                  type="file"
                  accept=".pdf"
                  onChange={handleFileUpload}
                  className="hidden"
                  ref={fileInputRef}
                />
                <div className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-2">
                  {file ? file.name : 'Click or drag a PDF here to upload'}
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  {file ? 'File selected' : 'PDF files only'}
                </div>
                {dragActive && (
                  <div className="absolute inset-0 bg-blue-100/60 dark:bg-blue-900/40 rounded-lg flex items-center justify-center pointer-events-none">
                    <span className="text-blue-700 dark:text-blue-200 font-semibold text-lg">Drop your PDF here</span>
                  </div>
                )}
              </div>
            </div>

            <button
              type="submit"
              className="bg-indigo-600 text-white px-6 py-2 rounded-lg font-semibold hover:bg-indigo-700 dark:hover:bg-indigo-500 transition self-end flex items-center gap-2"
              disabled={loading || !file}
            >
              {loading ? (
                <>
                  <Sparkles className="w-5 h-5 animate-pulse" />
                  Generating...
                </>
              ) : (
                <>
                  <RotateCcw className="w-5 h-5" />
                  Generate Flashcards
                </>
              )}
            </button>
            {error && <div className="text-red-500 mt-2 font-semibold">{error}</div>}
          </form>
        ) : (
          <div className="w-full flex flex-col gap-6 animate-slide-in mt-4">
            {/* Flashcard Display */}
            <div className="w-full bg-white dark:bg-zinc-900 rounded-xl shadow p-6 border border-gray-200 dark:border-zinc-700 min-h-[400px] flex flex-col relative">
              {/* Download Button */}
              <div className="absolute top-4 right-4 z-10">
                <PDFDownloadLink
                  document={<FlashcardPDF flashcards={flashcards} />}
                  fileName="flashcards.pdf"
                  style={{ textDecoration: 'none' }}
                >
                  {({ loading }) => (
                    <button
                      className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg font-semibold text-base shadow-md hover:bg-indigo-700 dark:hover:bg-indigo-500 transition focus:outline-none focus:ring-2 focus:ring-indigo-500"
                      title="Download as PDF"
                    >
                      <Download className="w-5 h-5" />
                      {loading ? 'Preparing PDF...' : 'Download PDF'}
                    </button>
                  )}
                </PDFDownloadLink>
              </div>

              {/* Flashcard Header */}
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100">Flashcards</h2>
                <div className="flex items-center gap-2">
                  <span className="text-sm text-gray-500 dark:text-gray-400">
                    {currentCard + 1} / {flashcards.length}
                  </span>
                  {flashcards.length === 5 && (
                    <span className="text-xs bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300 px-2 py-1 rounded-full">
                      Free Limit
                    </span>
                  )}
                </div>
              </div>

              {/* Flashcard Container */}
              <div className="flex-1 flex items-center justify-center">
                <div 
                  className={`relative w-full max-w-md h-64 cursor-pointer perspective-1000 ${currentCard === 4 && flashcards.length === 5 ? 'pointer-events-none' : ''}`}
                  onClick={handleFlip}
                >
                  {/* Front of Card */}
                  <div
                    className={`absolute inset-0 bg-white dark:bg-zinc-800 border-2 border-gray-200 dark:border-zinc-600 rounded-xl p-6 flex flex-col transition-all duration-500 ease-in-out ${flipped ? 'opacity-0 rotate-y-180' : 'opacity-100'} ${currentCard === 4 && flashcards.length === 5 ? 'blur-sm' : ''}`}
                  >
                    <div className="flex justify-between items-center mb-4">
                      <button
                        className="flex items-center gap-1 text-gray-700 dark:text-white/80 px-3 py-1 rounded-full hover:bg-gray-100 dark:hover:bg-white/10 transition-colors disabled:opacity-50"
                        onClick={(e) => {
                          e.stopPropagation();
                          setShowHint(!showHint);
                        }}
                        disabled={!currentFlashcard?.hint}
                      >
                        <Lightbulb
                          size={18}
                          className={currentFlashcard?.hint ? "text-yellow-500 dark:text-white" : "text-gray-400 dark:text-white/40"}
                        />
                        <span className="ml-1">Hint</span>
                      </button>
                      <div className="text-xs text-gray-500 dark:text-gray-400">Click to flip</div>
                    </div>
                    <div className="flex-1 flex items-center justify-center">
                      <p className="text-center text-xl font-medium text-gray-900 dark:text-gray-100">
                        {currentFlashcard?.question}
                      </p>
                    </div>
                  </div>

                  {/* Back of Card */}
                  <div
                    className={`absolute inset-0 bg-white dark:bg-zinc-800 border-2 border-gray-200 dark:border-zinc-600 rounded-xl p-6 flex flex-col transition-all duration-500 ease-in-out ${!flipped ? 'opacity-0 rotate-y-180' : 'opacity-100'} ${currentCard === 4 && flashcards.length === 5 ? 'blur-sm' : ''}`}
                  >
                    <div className="flex-1 flex items-center justify-center">
                      <p className="text-center text-lg text-gray-900 dark:text-gray-100">
                        {currentFlashcard?.answer}
                      </p>
                    </div>
                  </div>
                  {/* Overlay for 5th card */}
                  {currentCard === 4 && flashcards.length === 5 && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/40 rounded-xl z-10">
                      <p className="text-white text-lg font-semibold mb-4 text-center">Login to see and generate unlimited flashcards!</p>
                      <button
                        className="bg-indigo-600 text-white px-6 py-2 rounded-lg font-semibold hover:bg-indigo-700 transition"
                        onClick={() => setShowLoginModal(true)}
                      >
                        Login or Sign Up
                      </button>
                    </div>
                  )}
                </div>
              </div>

              {/* Hint Display */}
              {showHint && currentFlashcard?.hint && (
                <div className="mt-4 p-3 bg-yellow-100 dark:bg-yellow-500/10 rounded-lg">
                  <p className="text-yellow-700 dark:text-yellow-500 text-sm">{currentFlashcard.hint}</p>
                </div>
              )}

              {/* Navigation Controls */}
              <div className="flex justify-between items-center gap-4 mt-6">
                <button
                  className="w-12 h-12 flex items-center justify-center rounded-full text-gray-700 dark:text-white border border-gray-300 dark:border-white/10 hover:bg-gray-100 dark:hover:bg-white/10 transition-colors disabled:opacity-50"
                  onClick={handlePrev}
                  disabled={currentCard === 0}
                >
                  <ChevronLeft size={24} />
                </button>
                <span className="text-gray-500 dark:text-white/60 text-base">
                  {currentCard + 1} / {flashcards.length}
                </span>
                <button
                  className="w-12 h-12 flex items-center justify-center rounded-full text-gray-700 dark:text-white border border-gray-300 dark:border-white/10 hover:bg-gray-100 dark:hover:bg-white/10 transition-colors disabled:opacity-50"
                  onClick={handleNext}
                  disabled={currentCard === flashcards.length - 1}
                >
                  <ChevronRight size={24} />
                </button>
              </div>
              
              {/* Login prompt when on 5th card */}
              {currentCard === 4 && flashcards.length === 5 && (
                <div className="mt-4 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
                  <p className="text-blue-700 dark:text-blue-300 text-sm text-center">
                    Want more flashcards? <button 
                      className="underline font-semibold hover:text-blue-800 dark:hover:text-blue-200"
                      onClick={() => setShowLoginModal(true)}
                    >
                      Login or Sign Up
                    </button> to access unlimited flashcards!
                  </p>
                </div>
              )}
            </div>

            <button
              onClick={handleBack}
              className="w-full mt-4 bg-gray-200 dark:bg-zinc-800 text-gray-900 dark:text-gray-100 py-2 rounded-xl font-semibold shadow hover:bg-gray-300 dark:hover:bg-zinc-700 transition focus:outline-none focus:ring-2 focus:ring-indigo-500"
            >
              Back & Upload New File
            </button>
          </div>
        )}
      </div>
      <style jsx global>{`
        @keyframes fade-in {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in {
          animation: fade-in 0.6s cubic-bezier(0.4,0,0.2,1);
        }
        @keyframes slide-in {
          from { opacity: 0; transform: translateY(40px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-slide-in {
          animation: slide-in 0.7s cubic-bezier(0.4,0,0.2,1);
        }
        .perspective-1000 {
          perspective: 1000px;
        }
        .rotate-y-180 {
          transform: rotateY(180deg);
        }
        .blur-sm {
          filter: blur(4px);
        }
      `}</style>
    </main>
  );
} 